name: Test VEX Generation
on: [push]

jobs:
  generate_vex:
    runs-on: ubuntu-latest
    name: Test VEX Generation with Conjur OSS
    steps:
      - name: "Checkout code"
        id: checkout-code
        uses: actions/checkout@v4
        with:
          path: code

      - name: "Checkout Conjur OSS Helm Chart"
        id: checkout-conjur
        uses: actions/checkout@v4
        with:
          repository: cyberark/conjur-oss-helm-chart
          path: conjur-oss-helm-chart

      - name: "Generate dataKey for Conjur"
        id: generate-data-key
        shell: bash
        run: code/generate-data-key.sh

      - name: "Generate VEX with Kubescape"
        id: generate-vex
        uses: szh/generate-vex-action@main
        with:
          helm-chart-path: "conjur-oss-helm-chart/conjur-oss"
          install-timeout: 600s
          namespace: "conjur-oss"
          test-command: code/test.sh
